defaults: &defaults
  adapter: postgresql
  min_messages: WARNING
  pool: 10
  host: localhost
  port: 5432
  username: <%= ENV.fetch('DB_USERNAME', 'hello-thredded-6_dev').inspect %>
  password: <%= ENV.fetch('DB_PASSWORD', "hello-thredded-6").inspect %>
  encoding: utf8

development:
  <<: *defaults
  database: hello-thredded-6_dev

test:
  <<: *defaults
  database: hello-thredded-6_test


production:
  <<: *defaults
  encoding: utf8
  min_messages: WARNING
  database: <%= 'hello-thredded-6_dev' unless ENV['DATABASE_URL'] %>
  username: ""
  password: ""
